### ISSUE TITLE
Problems with installation

### ISSUE THREAD

**Issue by CarolynF10** [SWotherspoon/QPress#4]
Hej, 
When I try to install QPress I get an error message:

   --- re-building 'Mesocosm.Rmd' using rmarkdown
   Error: processing vignette 'Mesocosm.Rmd' failed with diagnostics:
   The 'rmarkdown' package should be installed and declared as a dependency of the 'QPress' package (e.g., in the 'Suggests' field of DESCRIPTION), because the latter contains vignette(s) built with the 'rmarkdown' package. Please see https://github.com/yihui/knitr/issues/1864 for more information.

If you check out the link at the bottom of the error message it explains what the problem is:
For package authors who use R Markdown vignettes based on the vignette engine knitr::knitr (or knitr::docco_linear, knitr::docco_classic, etc.), you should declare the (soft) dependency on markdown, e.g., in the package DESCRIPTION:

Suggests: markdown
VignetteBuilder: knitr
Previously they didn't need to do this because markdown has been a hard dependency of knitr (in Imports), so the availability of markdown is guaranteed by knitr, but I want to make markdown a soft dependency of knitr in the future.

I think most packages use the vignette engine knitr::rmarkdown to write vignettes now, but there may still be a few vignettes using the knitr::knitr engine, which depends on markdown. If I move markdown to Suggests in knitr, users have to make sure markdown is available to R CMD check. To achieve that, they have to add markdown to Suggests to their DESCRIPTION files.

Similarly, if your vignette is based on the vignette engine knitr::rmarkdown, you have to declare the dependency on rmarkdown, e.g.,

Suggests: rmarkdown
VignetteBuilder: knitr

**Comment by raymondben** [comment]
Hum, that's interesting, thanks! Should be fixed now, I think - try installing again.

**Comment by CarolynF10** [comment]
Hi!
Still getting an error message complaining about rmarkdown, here is the whole thing:
  
-  installing the package to build vignettes
  creating vignettes ...
  
   creating vignettes ... 
  
E  creating vignettes (7s)
   --- re-building 'Mesocosm.Rmd' using rmarkdown
   Warning in engine$weave(file, quiet = quiet, encoding = enc) :
     Pandoc (>= 1.12.3) not available. Falling back to R Markdown v1.
   Error: processing vignette 'Mesocosm.Rmd' failed with diagnostics:
   The 'markdown' package should be installed and declared as a dependency of the 'QPress' package (e.g., in the 'Suggests' field of DESCRIPTION), because the latter contains vignette(s) built with the 'markdown' package. Please see https://github.com/yihui/knitr/issues/1864 for more information.
   --- failed re-building 'Mesocosm.Rmd'
   
   --- re-building 'Snowshoe.Rmd' using rmarkdown
   Warning in engine$weave(file, quiet = quiet, encoding = enc) :
     Pandoc (>= 1.12.3) not available. Falling back to R Markdown v1.
   Error: processing vignette 'Snowshoe.Rmd' failed with diagnostics:
   The 'markdown' package should be installed and declared as a dependency of the 'QPress' package (e.g., in the 'Suggests' field of DESCRIPTION), because the latter contains vignette(s) built with the 'markdown' package. Please see https://github.com/yihui/knitr/issues/1864 for more information.
   --- failed re-building 'Snowshoe.Rmd'
   
   SUMMARY: processing the following files failed:
     'Mesocosm.Rmd' 'Snowshoe.Rmd'
   
   Error: Vignette re-building failed.
   Execution halted

Error: Failed to install 'QPress' from GitHub:
  System command 'Rcmd.exe' failed, exit status: 1, stdout + stderr (last 10 lines):
E>   Pandoc (>= 1.12.3) not available. Falling back to R Markdown v1.
E> Error: processing vignette 'Snowshoe.Rmd' failed with diagnostics:
E> The 'markdown' package should be installed and declared as a dependency of the 'QPress' package (e.g., in the 'Suggests' field of DESCRIPTION), because the latter contains vignette(s) built with the 'markdown' package. Please see https://github.com/yihui/knitr/issues/1864 for more information.
E> --- failed re-building 'Snowshoe.Rmd'
E> 
E> SUMMARY: processing the following files failed:
E>   'Mesocosm.Rmd' 'Snowshoe.Rmd'
E> 
E> Error: Vignette re-building failed.
E> Execution halted

**Comment by raymondben** [comment]
Well, at least it's a different error message now! Would you mind pasting the outputs of:
```
rmarkdown::pandoc_version()
```
and
```
sessionInfo()
```
please? 

(Alternatively, if you just need to get the package installed, you can try `remotes::install_github("SWotherspoon/QPress", build_vignettes = FALSE)`, which might avoid the problem. Of course you won't then have the vignettes on your local machine, but you can browse them on https://swotherspoon.github.io/QPress/)

**Comment by CarolynF10** [comment]
> rmarkdown::pandoc_version()
[1] ‘0’

> sessionInfo()
R version 4.0.5 (2021-03-31)
Platform: i386-w64-mingw32/i386 (32-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=Swedish_Sweden.1252  LC_CTYPE=Swedish_Sweden.1252   
[3] LC_MONETARY=Swedish_Sweden.1252 LC_NUMERIC=C                   
[5] LC_TIME=Swedish_Sweden.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ggplot2_3.3.3  reshape2_1.4.4 FCMapper_1.1   igraph_1.2.6  

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.6        pillar_1.6.0      compiler_4.0.5    plyr_1.8.6       
 [5] prettyunits_1.1.1 remotes_2.3.0     tools_4.0.5       digest_0.6.27    
 [9] testthat_3.0.2    pkgbuild_1.2.0    pkgload_1.2.1     evaluate_0.14    
[13] tibble_3.1.1      memoise_2.0.0     lifecycle_1.0.0   gtable_0.3.0     
[17] pkgconfig_2.0.3   rlang_0.4.10      cli_2.5.0         rstudioapi_0.13  
[21] curl_4.3          xfun_0.22         fastmap_1.1.0     knitr_1.33       
[25] dplyr_1.0.5       withr_2.4.2       stringr_1.4.0     generics_0.1.0   
[29] vctrs_0.3.7       desc_1.3.0        fs_1.5.0          devtools_2.4.0   
[33] tidyselect_1.1.0  rprojroot_2.0.2   grid_4.0.5        glue_1.4.2       
[37] R6_2.5.0          processx_3.5.1    fansi_0.4.2       rmarkdown_2.7    
[41] sessioninfo_1.1.1 farver_2.1.0      callr_3.7.0       purrr_0.3.4      
[45] magrittr_2.0.1    htmltools_0.5.1.1 scales_1.1.1      ps_1.6.0         
[49] ellipsis_0.3.1    usethis_2.0.1     colorspace_2.0-0  labeling_0.4.2   
[53] utf8_1.2.1        stringi_1.5.3     munsell_0.5.0     cachem_1.0.4     
[57] crayon_1.4.1    

Installing without vignettes is no problem! :-)

**Comment by raymondben** [comment]
Aha, `rmarkdown` is installed but it can't find `pandoc`. I suspect that this might be due to running a 32-bit version of R, but I'm kinda guessing that. I'll experiment when I have time, but unless you have particular reason to be using 32-bit R, it is probably better to use 64-bit.

**Comment by raymondben** [comment]
Nope, I'm not sure what's going on here. On my test machine, 32-bit Windows seems to find pandoc (which is bundled with RStudio) ok. But in any case it's not a QPress-specific issue, so I'll close this. I've updated the README to explain the option of installing without the vignettes.
